#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

ynh_abort_if_errors

get__remote_password() {
    echo ""
}

get__local_imap_password() {
    echo ""
}

set__remote_password() {
    if [ -z "${remote_password:-}" ]; then
        ynh_print_info "Remote IMAP password unchanged."
        return 0
    fi

    ynh_app_setting_set --key=remote_password --value="$remote_password"
    ynh_print_info "Remote IMAP password updated."
}

set__local_imap_password() {
    if [ -z "${local_imap_password:-}" ]; then
        ynh_print_info "Local IMAP password unchanged."
        return 0
    fi

    ynh_app_setting_set --key=local_imap_password --value="$local_imap_password"
    ynh_print_info "Local IMAP password updated."
}

ynh_app_config_apply() {
    _ynh_app_config_apply
    save_runtime_settings
    ensure_runtime_files
}

ynh_app_config_run "$1"
