#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

ynh_script_progression "Removing system configuration..."
ynh_config_remove_logrotate

if ynh_hide_warnings yunohost service status "$app" >/dev/null; then
    yunohost service remove "$app"
fi

remove_systemd_units

ynh_script_progression "Removal of $app completed"
