#!/bin/bash

source ../settings/scripts/_common.sh
source /usr/share/yunohost/helpers

ynh_script_progression "Restoring application files..."
ynh_restore "$install_dir"
chown -R "$app:$app" "$install_dir"

ynh_script_progression "Restoring runtime data..."
ynh_restore "$data_dir"
chown -R "$app:$app" "$data_dir"
fix_data_dir_permissions

ynh_script_progression "Restoring system services..."
ynh_restore "/etc/systemd/system/$app.service"
systemctl daemon-reload
systemctl enable "$app.service" --quiet
ynh_restore "/etc/logrotate.d/$app"
mkdir -p "/var/log/$app"
ynh_restore "/var/log/$app/" || true
chown -R "$app:$app" "/var/log/$app"
register_service

ynh_script_progression "Starting $app..."
ynh_systemctl --service="$app" --action="start"

ynh_script_progression "Restoration completed for $app"
