#!/bin/bash

source ../settings/scripts/_common.sh
source /usr/share/yunohost/helpers

ynh_script_progression "Restoring application files..."
ynh_restore "$install_dir"
chown -R "$app:$app" "$install_dir"

ynh_script_progression "Restoring runtime data..."
ynh_restore "$data_dir"
ensure_runtime_files

ynh_script_progression "Restoring system services..."
ynh_restore "/etc/systemd/system/$app.service"
ynh_restore "/etc/systemd/system/$app.timer"
systemctl daemon-reload
systemctl enable "$app.timer" --quiet
ynh_restore "/etc/logrotate.d/$app"
mkdir -p "/var/log/$app"
ynh_restore "/var/log/$app/" || true
chown -R "$app:$app" "/var/log/$app"
register_service

ynh_script_progression "Starting scheduler for $app..."
start_scheduler

ynh_script_progression "Restoration completed for $app"
